name: Generate and Save M3U Playlist

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Create cookies.txt from secret
        run: echo "$COOKIES_TXT" > cookies.txt
        env:
          COOKIES_TXT: ${{ secrets.COOKIES_TXT }}

      - name: Run Script to Generate Playlist
        run: python generate_m3u.py

      - name: Commit and Push playlist.m3u to Repository
        run: |
          git config --global user.name "Your GitHub Actions Bot"
          git config --global user.email "your-email@example.com"
          git add playlist.m3u
          git commit -m "Update playlist.m3u"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available to GitHub Actions

